# Generated by Django 5.1.3 on 2024-12-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_personalinfo_facebook_personalinfo_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
