# Generated by Django 5.1.3 on 2024-12-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_personalinfo_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
